### ISSUE TITLE
Setup the Space

### ISSUE THREAD

**Issue by NickoDante** [deprecatedcoder/PictureWindow#3]
Hello ! Greetings from Colombia.

I am very grateful to have shared this incredible project. But I've had some problems:

1) How have you configured the recognition space? I have a large space but I do not know if the project works better with the "Seated" configuration.
2) When performing each step that appears in the GitHub, the step of dragging the CameraRig Prefab to recognize the controls on the scene is still missing, right?
3) Since there is no Demo scene, I created my own scene but there is an error with respect to a Key in the directory: "KeyNotFoundException: The given key was not present in the dictionary." Any ideas?

Thank you again !

**Comment by NickoDante** [comment]
Hi ! 

I found the error in Number 3. In Update, the  box can be created , but the error shows when I don't Set up the corners. That why error pops up.

**Comment by hennesysott** [comment]
5144372269

**Comment by deprecatedcoder** [comment]
I think the latest release will address your concerns.  Let me know if you have any more issues and thanks for checking it out (and sorry for the slow response).
